### ISSUE TITLE
Openai update

### ISSUE THREAD

**Issue by danielgontz** [whatbirdisthat/cyberdolphin#5]
Hello,
Another plugin in comfyui is requesting openai > 1.0
and your plugin is using still the 0.2 version.
Can you please migrate to a newer version of openai ?

`You tried to access openai.Model, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

FETCH DATA from: D:\_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[ERROR] An error occurred while retrieving information for the '🐬 OpenAI Advanced' node.
Traceback (most recent call last):
  File "D:\_AI\ComfyUI_windows_portable\ComfyUI\server.py", line 418, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\_AI\ComfyUI_windows_portable\ComfyUI\server.py", line 396, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cyberdolphin\cyberdolphin_openai_advanced.py", line 13, in INPUT_TYPES
    openai_model_list = [m["id"] for m in openai.Model.list()['data']]
                                          ^^^^^^^^^^^^^^^^^
  File "D:\_AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_utils\_proxy.py", line 22, in __getattr__
    return getattr(self.__get_proxied__(), attr)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\_utils\_proxy.py", line 43, in __get_proxied__
    return self.__load__()
           ^^^^^^^^^^^^^^^
  File "D:\_AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\openai\lib\_old_api.py", line 33, in __load__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1:

You tried to access openai.Model, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface.

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742`

**Comment by whatbirdisthat** [comment]
hi @danielgontz thank you for all your help with cyberdolphin :)
It looks like a fairly straight-forward change, but it will take a couple of hours to re-write things, testing and etc.
Stay tuned :)

**Comment by whatbirdisthat** [comment]
@danielgontz cyberdolphin now requires openai compatible with v1.2.3 (latest as of today)
thanks again for your help :)
